[package]
name = "bevy_game"
version = "0.1.0"
publish = false
authors = ["f0kes <f0kesppokes@gmail.com>"]
edition = "2021"
exclude = ["dist", "build", "assets", "credits"]

[workspace]
members = [
    "crates/camera",
    "crates/combat",
    "crates/input_actions",
    "crates/meta_components",
    "crates/misc",
    "crates/movement",
    "crates/outline",
    "crates/ownership",
    "crates/steering",
    "crates/world_gen",
    "crates/meta_macro_derive",
     "crates/easy_model_load",
]

[workspace.dependencies]
bevy = {version = "0.15.2", default-features = true}
bevy_asset_loader = "0.22.0"
bevy_hanabi = "0.14.0"
bevy-inspector-egui = "0.28"
bevy_spatial = { git = "https://github.com/VitalyArtemiev/bevy-spatial", branch = "within" }
rand = "0.9.0"
serde = { version = "1.0.215", features = ["derive"] }
ron = "0.8.1"
winit = { version = "0.30", default-features = false }
image = { version = "0.25", default-features = false }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
thiserror= {version= "2.0.11"}
avian3d = "0.2.1"
bevy_tweening = "0.12.0" 
vleue_navigator = {version="0.11.1", features= ["avian3d"]}


movement = { path = "./crates/movement" }
input_actions = { path = "./crates/input_actions" }
outline = { path = "./crates/outline" }
ownership = { path = "./crates/ownership" }
camera = { path = "./crates/camera" }
steering = { path = "./crates/steering" }
combat = { path = "./crates/combat" }
meta_components = { path = "./crates/meta_components" }
misc = { path = "./crates/misc" }
world_gen = { path = "./crates/world_gen" }
easy_model_load = { path = "./crates/easy_model_load" }

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_hanabi = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
avian3d = { workspace = true }
bevy_spatial = { workspace = true }
bevy-inspector-egui = { workspace = true }
vleue_navigator = { workspace = true }


movement = { workspace = true }
input_actions = { workspace = true }
outline = { workspace = true }
ownership = { workspace = true }
camera = { workspace = true }
steering = { workspace = true }
combat = { workspace = true }
meta_components = { workspace = true }
misc = { workspace = true }
world_gen = { workspace = true }
easy_model_load = { workspace = true }

# Local crates


[features]
dev = ["bevy/dynamic_linking"]
default = ["dev"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[profile.dist]
inherits = "release"
opt-level = 3

[build-dependencies]
embed-resource = "3.0.1"
